#!/bin/bash
#PBS -V
#PBS -l nodes=node19:ppn=56,mem=128gb
#PBS -l walltime=500:00:00
#PBS -N chamaea_admixture
#PBS -j oe
#PBS -o /usr/scratch2/userdata2/mtofflemire/projects/chamaea/2026_WD/03_admixture/admixture.log
#PBS -q batch

set -euo pipefail

cd "$PBS_O_WORKDIR" || exit 1

source ~/miniconda3/etc/profile.d/conda.sh
conda activate plink19



#define paths
VCF="/usr/scratch2/userdata2/mtofflemire/projects/chamaea/2026_WD/01_VARIANTS/Chamaea_auto_filteredQC_maf0.05_hwe0.01_prune1kb.vcf.gz"
RESULTS="/usr/scratch2/userdata2/mtofflemire/projects/chamaea/2026_WD/03_admixture"
PREFIX="Chamaea_auto_filteredQC_maf0.05_hwe0.01_prune1kb"
BED_PREFIX="${RESULTS}/${PREFIX}"
ADMIX="/usr/scratch2/userdata2/mtofflemire/softs/admixture_linux-1.3.1/admixture"

mkdir -p "$RESULTS"



#make necesarry plink files
plink --vcf "$VCF" \
      --make-bed \
      --out "$BED_PREFIX" \
      --set-missing-var-ids @:# \
      --allow-extra-chr \
      --double-id



#fix issue with names in plink bed files
awk 'BEGIN { OFS="\t" } { $1 = 0; print }' "${BED_PREFIX}.bim" > "${BED_PREFIX}.bim.tmp"
mv "${BED_PREFIX}.bim.tmp" "${BED_PREFIX}.bim"




#run admixture
SEED=43
RUN_DIR="${RESULTS}/seed${SEED}"
mkdir -p "$RUN_DIR"
cd "$RUN_DIR" || exit 1

for K in {1..10}; do
    "$ADMIX" -s "$SEED" --cv=10 -j48 "${BED_PREFIX}.bed" "$K" > "log${K}_seed${SEED}.out"
done
